version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/core-data-loading
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install --quiet
      - run:
          name: Run ESLint
          command: npm run lint
      - setup_remote_docker
      - run:
          name: Spin up environment
          command: |
            ACCEPT_EULA=yes docker-compose up -d
            docker cp ./data qix-engine:/
      - run:
          name: Run Integration Tests
          command: |
            docker cp ./ node-test-runner:./
            docker exec node-test-runner sh -c 'cd ./reload-runner && TEST_HOST=qix-engine node index.js'
