version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/core-data-loading
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install --quiet
      - run:
          name: Run ESLint
          command: npm run lint
      - setup_remote_docker
      - run:
          name: Spin up environment
          command: ACCEPT_EULA=yes docker-compose up -d
      - run:
          name: Run Integration Tests
          working_directory: /core-data-loading/reload-runner
          command: |
            docker exec node-test-runner sh -c 'npm install'
            docker exec node-test-runner sh -c 'TEST_HOST=qix-engine node index.js'
